"""update books table

Revision ID: 2d19c3e6417b
Revises: d6d12d417afc
Create Date: 2025-08-02 12:45:43.247935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d19c3e6417b'
down_revision: Union[str, Sequence[str], None] = 'd6d12d417afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author_id', sa.Integer(), nullable=False))
    op.add_column('books', sa.Column('genre_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('books_author_fkey'), 'books', type_='foreignkey')
    op.drop_constraint(op.f('books_genre_fkey'), 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'genres', ['genre_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'books', 'authors', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_column('books', 'genre')
    op.drop_column('books', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('books', sa.Column('genre', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key(op.f('books_genre_fkey'), 'books', 'genres', ['genre'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('books_author_fkey'), 'books', 'authors', ['author'], ['id'], ondelete='CASCADE')
    op.drop_column('books', 'genre_id')
    op.drop_column('books', 'author_id')
    # ### end Alembic commands ###
