"""add trigram index to languages

Revision ID: 8edc6657a15f
Revises: 531687f4114a
Create Date: 2025-08-15 16:01:51.143451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8edc6657a15f'
down_revision: Union[str, Sequence[str], None] = '531687f4114a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('languages_name_en_trgm', 'languages', ['name_en'], unique=False, postgresql_using='gin', postgresql_ops={'name_en': 'gin_trgm_ops'})
    op.create_index('languages_name_ru_trgm', 'languages', ['name_ru'], unique=False, postgresql_using='gin', postgresql_ops={'name_ru': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('languages_name_ru_trgm', table_name='languages', postgresql_using='gin', postgresql_ops={'name_ru': 'gin_trgm_ops'})
    op.drop_index('languages_name_en_trgm', table_name='languages', postgresql_using='gin', postgresql_ops={'name_en': 'gin_trgm_ops'})
    # ### end Alembic commands ###
