"""all languages table

Revision ID: 92933b07e67c
Revises: c4b3fa33b1ec
Create Date: 2025-08-05 14:51:11.588263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92933b07e67c'
down_revision: Union[str, Sequence[str], None] = 'c4b3fa33b1ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

LANGUAGES = [
    {'code': 'ar', 'name_en': 'Arabic', 'name_ru': 'Арабский'},
    {'code': 'be', 'name_en': 'Belarusian', 'name_ru': 'Белорусский'},
    {'code': 'bg', 'name_en': 'Bulgarian', 'name_ru': 'Болгарский'},
    {'code': 'cs', 'name_en': 'Czech', 'name_ru': 'Чешский'},
    {'code': 'da', 'name_en': 'Danish', 'name_ru': 'Датский'},
    {'code': 'de', 'name_en': 'German', 'name_ru': 'Немецкий'},
    {'code': 'el', 'name_en': 'Greek', 'name_ru': 'Греческий'},
    {'code': 'en', 'name_en': 'English', 'name_ru': 'Английский'},
    {'code': 'es', 'name_en': 'Spanish', 'name_ru': 'Испанский'},
    {'code': 'et', 'name_en': 'Estonian', 'name_ru': 'Эстонский'},
    {'code': 'fi', 'name_en': 'Finnish', 'name_ru': 'Финский'},
    {'code': 'fr', 'name_en': 'French', 'name_ru': 'Французский'},
    {'code': 'he', 'name_en': 'Hebrew', 'name_ru': 'Иврит'},
    {'code': 'hi', 'name_en': 'Hindi', 'name_ru': 'Хинди'},
    {'code': 'hu', 'name_en': 'Hungarian', 'name_ru': 'Венгерский'},
    {'code': 'id', 'name_en': 'Indonesian', 'name_ru': 'Индонезийский'},
    {'code': 'it', 'name_en': 'Italian', 'name_ru': 'Итальянский'},
    {'code': 'ja', 'name_en': 'Japanese', 'name_ru': 'Японский'},
    {'code': 'kk', 'name_en': 'Kazakh', 'name_ru': 'Казахский'},
    {'code': 'ko', 'name_en': 'Korean', 'name_ru': 'Корейский'},
    {'code': 'lt', 'name_en': 'Lithuanian', 'name_ru': 'Литовский'},
    {'code': 'lv', 'name_en': 'Latvian', 'name_ru': 'Латышский'},
    {'code': 'nl', 'name_en': 'Dutch', 'name_ru': 'Голландский'},
    {'code': 'no', 'name_en': 'Norwegian', 'name_ru': 'Норвежский'},
    {'code': 'pl', 'name_en': 'Polish', 'name_ru': 'Польский'},
    {'code': 'pt', 'name_en': 'Portuguese', 'name_ru': 'Португальский'},
    {'code': 'ro', 'name_en': 'Romanian', 'name_ru': 'Румынский'},
    {'code': 'ru', 'name_en': 'Russian', 'name_ru': 'Русский'},
    {'code': 'sk', 'name_en': 'Slovak', 'name_ru': 'Словацкий'},
    {'code': 'sl', 'name_en': 'Slovenian', 'name_ru': 'Словенский'},
    {'code': 'sv', 'name_en': 'Swedish', 'name_ru': 'Шведский'},
    {'code': 'tr', 'name_en': 'Turkish', 'name_ru': 'Турецкий'},
    {'code': 'uk', 'name_en': 'Ukrainian', 'name_ru': 'Украинский'},
    {'code': 'uz', 'name_en': 'Uzbek', 'name_ru': 'Узбекский'},
    {'code': 'vi', 'name_en': 'Vietnamese', 'name_ru': 'Вьетнамский'},
    {'code': 'zh', 'name_en': 'Chinese', 'name_ru': 'Китайский'},
]

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name_ru', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )

    languages_table = sa.table(
        'languages',
        sa.column('code', sa.String(2)),
        sa.column('name_ru', sa.String()),
        sa.column('name_en', sa.String()),
    )
    op.bulk_insert(languages_table, LANGUAGES)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('languages')
    # ### end Alembic commands ###
