"""admin moderation

Revision ID: 9d66d5438ec1
Revises: 8edc6657a15f
Create Date: 2025-08-15 16:03:41.420134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d66d5438ec1'
down_revision: Union[str, Sequence[str], None] = '8edc6657a15f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the ENUM type
    approval_status_enum = postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus')
    approval_status_enum.create(op.get_bind())
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('approval_status', postgresql.ENUM(name='approvalstatus'), server_default='PENDING', nullable=False))
    op.add_column('books', sa.Column('moderation_reason', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('books', 'moderation_reason')
    op.drop_column('books', 'approval_status')
    # ### end Alembic commands ###
    
    # Drop the ENUM type
    approval_status_enum = postgresql.ENUM(name='approvalstatus', create_type=False)
    approval_status_enum.drop(op.get_bind())
