"""add like index to book_events

Revision ID: c4b3fa33b1ec
Revises: 4615d689e6d7
Create Date: 2025-08-05 03:23:43.964918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4b3fa33b1ec'
down_revision: Union[str, Sequence[str], None] = '4615d689e6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uix_book_event_like', 'book_events', ['book_id', 'user_id'], unique=True, postgresql_where=sa.text("interaction = 'LIKE'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_book_event_like', table_name='book_events', postgresql_where=sa.text("interaction = 'LIKE'"))
    # ### end Alembic commands ###
