"""update exchange_locations table

Revision ID: d6d12d417afc
Revises: bfdda45a2244
Create Date: 2025-08-02 03:07:04.870598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6d12d417afc'
down_revision: Union[str, Sequence[str], None] = 'bfdda45a2244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_locations', sa.Column('title', sa.String(), nullable=False))
    op.add_column('exchange_locations', sa.Column('description', sa.String(), nullable=True))
    op.add_column('exchange_locations', sa.Column('opening_hours', sa.String(), nullable=True, comment='OSM format: Mo-Fr 09:00-19:00; Sa ...'))
    op.add_column('exchange_locations', sa.Column('address', sa.String(), nullable=False))
    op.add_column('exchange_locations', sa.Column('directions', sa.String(), nullable=True, comment='Как добраться'))
    op.drop_column('exchange_locations', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_locations', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('exchange_locations', 'directions')
    op.drop_column('exchange_locations', 'address')
    op.drop_column('exchange_locations', 'opening_hours')
    op.drop_column('exchange_locations', 'description')
    op.drop_column('exchange_locations', 'title')
    # ### end Alembic commands ###
