"""update books table

Revision ID: dc67d7008daa
Revises: edaaccc60157
Create Date: 2025-08-02 17:28:54.659716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc67d7008daa'
down_revision: Union[str, Sequence[str], None] = 'edaaccc60157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_city_id'), table_name='books')
    op.drop_constraint(op.f('books_city_id_fkey'), 'books', type_='foreignkey')
    op.drop_column('books', 'city_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('books_city_id_fkey'), 'books', 'cities', ['city_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_books_city_id'), 'books', ['city_id'], unique=False)
    # ### end Alembic commands ###
