"""update user table

Revision ID: eae786bd2dac
Revises: c8c7d89089f9
Create Date: 2025-08-01 17:29:34.430684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eae786bd2dac'
down_revision: Union[str, Sequence[str], None] = 'c8c7d89089f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


gender_enum = postgresql.ENUM(
    "MALE", "FEMALE", "UNKNOWN",
    name="gender",
    create_type=False
)


def upgrade() -> None:
    """Upgrade schema."""
    gender_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('gender', gender_enum, nullable=True))
    op.drop_column('users', 'favorite_genres')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_genres', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_column('users', 'gender')
    op.drop_column('users', 'birth_date')
    
    gender_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
